<!---
[settings]
dsn=galleon2
perpage=10
fromAddress=galleon@localhost.com
rootURL=http://127.0.0.1/forums
sendonpost=youremail@goeshere.com
dbtype=mysql
tableprefix=galleon_
version=2.2.9.002
requireconfirmation=true
title=Galleon Forums
fullemails=true
encryptpasswords=false
allowavatars=true
safeExtensions=zip,tar,jpg,gif,png,wpd,doc,pdf,xls,ppt,txt,odt
bbcode_editor=true
mailserver=
mailusername=
mailpassword=
--->
